# -*- coding: utf-8 -*-
"""madlibs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnrT6_oFCsow9bQ7SaQrwXq_YoKMt_Tz
"""

# string concatenation  (aka how to put strings together)
# suppose we want to create a string that says "subscribe to _____"
# youtuber = "Merve Komur" #some string available

# a few ways to do this
# print("subscribe to " + youtuber)
# print("subscribe to {}".format(youtuber))
# print(f"subscribe to {youtuber}")

adj = input ("Adjective:")
verb1 = input("Verb: ")
verb2 = input("Verb: ")
famous_person = input("Famous person: ")

madlib = f"Computer programming is so {adj}! It makes me so excited all the time because \
    I love to {verb1}. Stay hydrated and {verb2} like you are {famous_person}!"

print(madlib)